first page , second page , third page , footer
noorim-project/NFS_Front pull request #13
Opened 2019-07-21 12:55 UTC by sema0710

첫번째 메인 페이지 , 공지사항 , 시간표 , footer를 제작하였고,
확대 및 축소 시에 일어날 수 있는 버그들을 수정하였습니다.

2019-07-22 04:55 UTC, junu126 requested changes
전체적으로 네이밍 체크 해주세요.

화이팅

2019-07-22 04:55 UTC, junu126 commented on src/assets/Main/index.js
> +export {Cloud , Facebook , School , DMS};
이미지를 import해오면서 네이밍이 부적절한 것 같아요. 딱 보면 이미지처럼 보이게 바꿔주세요.

2019-07-22 04:55 UTC, junu126 commented on src/components/Main/Main.jsx
> +  </S.MainComponent>
네이밍을 바꿔야 할 것 같아요.
각 컴포넌트의 역할을 네이밍으로 표현해주세요

2019-07-22 04:55 UTC, junu126 commented on src/components/Main/MainFirstPage.jsx
> +const HeaderFirstPage = ()=> {
import랑 띄워주세요.

그리고 네이밍도..

2019-07-22 04:55 UTC, junu126 commented on src/components/Main/MainNoticeTable.jsx
> +          <MainNoticeContent name="오준상" number="6" date="2019-07-10" content="와 NFS 너무 유용해!"/>
나중가면 서버에서 받아올 데이터들 입니다.
서버에서 List형식으로 데이터를 보내줄거에요. - name, number, date, content다.
이걸 map함수써서 한번에 처리할 수 있도록 코드 구현해주세요.

```javascript
    [서버데이터].map((data, index) => <MainNoticeContent name={data.name} number={index} date={data.date} content={data.content} />);
```

그리고 `number`라는 네이밍 부적절해보입니다.

2019-07-22 04:55 UTC, junu126 commented on src/styles/gloobalStlye.js
> +margin-left: ${props => props.togle  ? 0 : "-640px"};
GlobalStyle은 말 그대로 범용적으로 사용되는 styled들 입니다.

styled를 새롭게 만드는 것이 좋을 것 같습니다.

2019-07-24 00:36 UTC, sema0710 commented on src/assets/Main/index.js
> +export {Cloud , Facebook , School , DMS};
확인했습니다!!

2025-10-22 06:17 UTC, closed without merging